---
title: "[Python Debugging] IndexError:  list index out of range when Using Openpyxl"
seoTitle: "[Python Debugging] IndexError:  list index out of range when Using Ope"
seoDescription: "I left the excel file with no changes. I did not center-align the cell, and I also did not modify the cell width. After all that, IndexError:  list index ou"
datePublished: Sat Jan 04 2025 03:16:04 GMT+0000 (Coordinated Universal Time)
cuid: cm5hm3k22000308ky7qx231z0
slug: python-debugging-indexerror-list-index-out-of-range-when-using-openpyxl
cover: https://cdn.hashnode.com/res/hashnode/image/upload/v1735959514994/fed97886-0b2d-46ad-a172-317c497594e8.gif
ogImage: https://cdn.hashnode.com/res/hashnode/image/upload/v1735960547035/f27e784b-4379-4540-aa82-a667878add4e.gif
tags: python, error-handling, debugging, openpyxl, indexerror

---

---

## Error

I was working on my mini project called ***Schedulize,*** and an error occured while loading a workbook using openpyxl.

```python
def create_excel_file(self):
    wb = load_workbook(self.file_path) # IndexError:  list index out of range
    ws = wb.active
    ws['A1'] = f"{self.duty_date.year} {self.duty_date.month}"
    ws.column_dimensions['A'].width = 25

    self.fill_in_dates(wb, ws)
    self.fill_in_people(wb, ws)
    wb.save(self.file_path)
```

At first, I had no idea what the error meant because it said that list index is out of range. My code was just to load a workbook (excel file) and modify it, so it had nothing to do with lists. After googling and asking chatGPT, I found out that it was a problem with styling. In my case, I set the cell width to 25 by doing this: `ws.column_dimensions['A'].width = 25`. However, the cell width I set in my excel file was much bigger than 25. So, there was a crash. Furthermore, I did not make it center-align in my code, but I did center-align in the excel file that Iâ€™m loading, so there was a crash as well.

---

## Solution

I left the excel file with no changes. I did not center-align the cell, and I also did not modify the cell width. After all that, `IndexError: list index out of range` did not occur.